# the username and password values were created by
# echo -n 'admin' | base64
# echo -n '1f2d1e2e67df' | base64
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  mysql.properties: |
    host=192.168.1.100
    port=3306
---
apiVersion: v1
kind: Pod
metadata:
  name: projected-volume-example
  labels:
    zone: test-zone
    cluster: test-cluster
spec:
  containers:
  - name: client-container
    image: busybox
    command: ["sh", "-c", "sleep 360000"]
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: mysecret
          items:
          - key: username
            path: "my-username"
          - key: password
            path: "my-password"
      - downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
      - configMap:
          name: myconfigmap
          items:
          - key: mysql.properties
            path: "my-config"
