apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 512Mi
  persistentVolumeReclaimPolicy: Retain 
  rbd:
    image: pv-static
    keyring: /etc/ceph/keyring
    monitors:
    - 192.168.0.21:6789
    - 192.168.0.23:6789
    - 192.168.0.24:6789
    pool: tenx-pool
    secretRef:
      name: tenx-rbd0
    user: admin
  storageClassName: tenx-static
